### ISSUE TITLE
Use icons for nodes

### ISSUE THREAD

**Issue by NybyDK** [NybyDK/MPLS-Simulation#41]
Find suitable icons for customer, edge, and core, maybe all the same and a different color, or different icons
Please do not import a library that imports 10000 icons that all have to be transformed and built like we did in Ecdar :((((

**Comment by JakobTopholt** [comment]
Imma peep this one.

**Comment by JakobTopholt** [comment]
I think this [one](https://commons.wikimedia.org/wiki/File:Router.svg), with light blue for CE, yellow for LER, and pinkish for LSR would work
![310px-Router svg](https://github.com/NybyDK/MPLS-Simulation/assets/74545500/adc7ae3d-7412-4de6-9a1b-0ea24a346a65)


Currently we generate our own circles, if we inserted these instead we'd need a way of inserting the text on them

**Comment by JakobTopholt** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients

Also, we could just strip it of all color and gradient it form slightly dark color to slightly light color from like the top left to the bottom right

**Comment by JakobTopholt** [comment]
Related to #139
